<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    '0941da88a3052b85806ae48fb60c05ed' => $vendorDir . '/aimeos/map/src/function.php',
    '89728299c194c4487ca94219babf542f' => $vendorDir . '/typo3/autoload-include.php',
);
